In [6]:
import numpy as np
# 行與列之間的釐清
# 範例1-計算最大值
def max_value(x):
    return np.max(x)
# 二維數組
arr = np.array([[1,2,3],[4,5,6]])

[4 5 6]


In [7]:
# 應用函數
max_in_columns = np.apply_along_axis(max_value, 0, arr) #計算每一列最大值
print(max_in_columns)

[4 5 6]


In [8]:
max_in_rows = np.apply_along_axis(max_value, 1, arr) #計算每一行最大值
print(max_in_rows)

[3 6]


In [9]:
# 範例2-計算範圍(最大值-最小值)
# 自定義函數
def range_value(x):
    return np.max(x) - np.min(x)

In [11]:
# 應用函數
range_in_columns = np.apply_along_axis(range_value, 0, arr)
print(range_in_columns)

[3 3 3]


In [12]:
range_in_rows = np.apply_along_axis(range_value, 1, arr)
print(range_in_rows)

[2 2]
