In [57]:
import numpy as np

In [58]:
# 1.創建數組
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [59]:
# 2.數組操作
print(f'原始:{arr}\n'
      f'+2:{arr+2}\n'
      f'*2:{arr*2}')

原始:[1 2 3 4 5]
+2:[3 4 5 6 7]
*2:[ 2  4  6  8 10]


In [60]:
# 3.多維數組
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [61]:
# 4.數組索引和切片
print(arr[0]) #取得第一個元素
print(arr[1:3]) #取得第二到第三個元素(list)

1
[2 3]


In [62]:
# 5.數組函數
print(np.sum(arr)) #數組求和
print(np.mean(arr)) #數組球平均

15
3.0
