In [44]:
import numpy as np

In [45]:
# 1.多維度數組操作
# 創建3x3的數組
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
# 獲取第二行元素
second_row = arr[1,:]
print(second_row)

[4 5 6]


In [47]:
# 獲取第三列元素
third_row = arr[:, 2]
print(third_row)

[3 6 9]


In [48]:
# 轉置數組
transposed = arr.T
print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [49]:
# 2.數組的廣播
# 創建兩個不同形狀的數組
a = np.array([1,2,3])
b = np.array([[0],[1],[2]])
# 廣播追加
c = a+b
print(c)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [50]:
# 3.線性代數的運用
# 矩陣乘法
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])
product = np.dot(x,y,)
print(product)

[[19 22]
 [43 50]]


In [51]:
# 4.統計分析
data = np.array([1,2,3,4,5])
# 平均值(Mean)
mean = np.mean(data)
print(mean)

3.0


In [52]:
# 中位數(Median)
median = np.median(data)
print(median)

3.0


In [53]:
# 標準差(Standard Deviation)
standard_deviation = np.std(data)
print(standard_deviation)

1.4142135623730951


In [54]:
# 5.數據處理
# 處理缺失的數據
data_with_nan = np.array([1, np.nan,3 ,4 ,5])
clean_data = data_with_nan[~np.isnan(data_with_nan)]
print(data_with_nan,clean_data)

[ 1. nan  3.  4.  5.] [1. 3. 4. 5.]


In [55]:
# 數組排序
unsorted = np.array([1,4,3,2,5])
sorted_arr = np.sort(unsorted)
print(sorted_arr)

[1 2 3 4 5]


In [56]:
# 6.自定義函數與apply_along_axis
def my_func(x):
    return x * x
arr = np.array([[1,2,3],[4,5,6]])
result = np.apply_along_axis(my_func, 0, arr)
print(result)

[[ 1  4  9]
 [16 25 36]]


In [57]:
result = np.apply_along_axis(my_func, 0, arr)
print(result)

[[ 1  4  9]
 [16 25 36]]


In [58]:
def my_func(x):
    return np.sum(x)
result = np.apply_along_axis(my_func, 1, arr)
print(result)

[ 6 15]


In [59]:
def my_func(x):
    return np.max(x)
result = np.apply_along_axis(my_func, 0, arr)
print(result)

[4 5 6]
