In [39]:
import numpy as np

In [40]:
# 1.多維度數組操作
# 創建3x3的數組
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
# 獲取第二行元素
second_row = arr[1,:]
print(second_row)

[4 5 6]


In [43]:
# 獲取第三列元素
third_row = arr[:, 2]
print(third_row)

[3 6 9]


In [45]:
# 轉置數組
transposed = arr.T
print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [46]:
# 2.數組的廣播
# 創建兩個不同形狀的數組
a = np.array([1,2,3])
b = np.array([[0],[1],[2]])
# 廣播追加
c = a+b
print(c)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [49]:
# 3.線性代數的運用
# 矩陣乘法
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
product = np.dot(x,y,)
print(product)

[[19 22]
 [43 50]]
